import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect,useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const deleteChannel = async (id) => {
    await axios.delete(`/api/channels/${id}`)
    setChannels(channels.filter((channel) => channel.id !== id))
  }
  const [channels, setChannels] = useState([])

  useEffect(() => {
    axios.get("/api/channels/").then((res) => {
      console.log(res.data);
      setChannels(res.data);
    })
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        {channels.map((channel) => (
          <div key={channel.id}>
            <h1>{channel.name}</h1>
            <p>{channel.created}</p>
            <button onClick={()=>{deleteChannel(channel.id)}}>Delete</button>
          </div>
        ))}

      </main>
    </>
  )
}
